default: all

all:
	rm -rf emit output
	export PATH=$(PATH):$(PWD)/coverity/prevent-linux-2.4.6/bin;	\
		cov-configure -co /usr/bin/gcc;								\
		./configure && make clean;									\
		cov-build -e emit -o output make
	mv README README.save
	mv README.COVERITY README
	tar czvf libpst.tgz README emit output
	mv README README.COVERITY
	mv README.save README
	rm -rf emit output
	echo mv libpst.tgz /home/httpd/html/510sg
	echo fixup-510 ns1 --dry-run

