Document: libpst
Title: Debian libpst Manual
Author: <insert document author here>
Abstract: This manual describes what libpst is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpst/libpst.sgml.gz

Format: postscript
Files: /usr/share/doc/libpst/libpst.ps.gz

Format: text
Files: /usr/share/doc/libpst/libpst.text.gz

Format: HTML
Index: /usr/share/doc/libpst/html/index.html
Files: /usr/share/doc/libpst/html/*.html

  
