//
// this file only exists to allow including <libpst/config.h>
// while building this package. The real config.h is at the
// top level, generated by ./configure, and installed into
// $includepath/libpst

#include "../config.h"

